### ISSUE TITLE
Convert from json to locres

### ISSUE THREAD

**Issue by brtraducoes** [sgkoishi/LocresReader#1]
Hi, is it possible to convert from json to locres?

**Comment by sgkoishi** [comment]
I didn't implement that since I don't need it right now :) 

If you know the version of your locres, you may replace those "read" into "write" in the program. Currently, I've covered the version 1 and 2, which is used by the game I'm targeting. 

Also you can probably use Unreal Engine itself to make a simple dummy game, which it should convert your input to locres file.



*Added*
I didn't dig into the logic but just analyzing the binary, so you may see some "magic" reads that the value is discarded
https://github.com/sgkoishi/LocresReader/blob/ca0a619f9d9492f55e83168c74416812e06c31d5/LocresReader/Program.cs#L20
https://github.com/sgkoishi/LocresReader/blob/ca0a619f9d9492f55e83168c74416812e06c31d5/LocresReader/Program.cs#L30-L31
They might be not that useful, or I don't care, ignoring them still works if I just want to read the content. However, you may need to read the source code of Unreal or learn/guess what those are for.
